FROM nvidia/cuda:12.8.1-base-ubuntu22.04 as base

# Set non-interactive frontend and timezone
ENV DEBIAN_FRONTEND=noninteractive

# Replace with your timezone if preferred
RUN ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone

########################
# Dependencies Install #
########################

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-venv \
    gcc \
    g++ \
    git \
    libgl1 \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libssl-dev \
    pkg-config \
    sed \
    tzdata \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

FROM base as base-user

#######################
# Setup Non-Root User #
#######################

# Create working directory and home directory for UID 1000
RUN mkdir -p /app /home/1000 /output_data /opt/venv /opt/models \
    && chown 1000:1000 /app /home/1000 /output_data /opt/venv /opt/models

# Set home directory for UID 1000
ENV HOME=/home/1000

# Switch to non-root user (UID 1000)
USER 1000

FROM base-user as dependency-base

############################################
# Setup Rust Dependencies for Transformers #
############################################

# Build Argument to override the version of Stable Diffusion
ARG RUST_TOOLCHAIN="1.18.0"
ENV RUST_TOOLCHAIN=$RUST_TOOLCHAIN

# Install rustup and Rust toolchain, sourcing env to update PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUST_TOOLCHAIN 
ENV PATH="/home/1000/.cargo/bin:${PATH}"

# Set working directory
WORKDIR /app

####################################
# Setup Common Python Dependencies #
####################################

# Create virtual environment
RUN python3.10 -m venv /opt/venv && /opt/venv/bin/pip install --upgrade pip setuptools wheel

# Install Python dependencies with Python 3.10
RUN /opt/venv/bin/pip install --no-cache-dir torch==2.7.0+cu128 torchvision==0.22.0+cu128 torchaudio==2.7.0+cu128 --index-url https://download.pytorch.org/whl/cu128
RUN /opt/venv/bin/pip install --no-cache-dir xformers==0.0.30 pillow==10.4.0 numpy==1.26.4 

COPY ./podman/deps/* /opt/dependencies/
CMD ["/opt/venv/bin/python3.10"]

FROM dependency-base as sd-webui-base

########################################
# Setup Automatic1111 Stable Diffusion #
########################################

# Set Stable Diffusion release version (default to v1.10.1 commit hash)
ARG STABLE_HASH=82a973c04367123ae98bd9abdf80d9eda9b910e2
ENV STABLE_HASH=$STABLE_HASH

# Clone Stable Diffusion and checkout specified release or fallback to stable commit
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git . \
   && git checkout "$STABLE_HASH" \
   && /opt/venv/bin/pip install --no-cache-dir -r /opt/dependencies/sd-webui.requirements.lock \
   && rm -rf .git /home/1000/.cache/pip

FROM sd-webui-base as webui

EXPOSE 7860

# Run web UI using virtual environment's Python
CMD ["/opt/venv/bin/python3.10", "launch.py", "--listen", "--port", "7860"]

FROM dependency-base as comfyui-base 

#################
# Setup ComfyUI #
#################

# Set ComfyUI release version (default to v0.3.34 commit hash)
ARG COMFY_HASH=158419f3a0017c2ce123484b14b6c527716d6ec8
ENV COMFY_HASH=$COMFY_HASH

# Clone ComfyUI and checkout specified release or fallback to stable commit
RUN git clone https://github.com/comfyanonymous/ComfyUI.git . \
    && git checkout "$COMFY_HASH" \
    && /opt/venv/bin/pip install --no-cache-dir -r /opt/dependencies/comfyui.requirements.lock \
    && rm -rf .git /home/1000/.cache/pip

FROM comfyui-base as comfyui

COPY ./extra_model_paths.yaml ./
EXPOSE 7861

# Run web UI using virtual environment's Python
CMD ["/opt/venv/bin/python3.10", "main.py", "--listen", "0.0.0.0", "--port", "7861"]

FROM dependency-base as ace-base

#############
# Setup ACE #
#############

ARG ACE_VERSION=330cc0eeb412430d9c551485ec726a5891bf1aef
ENV ACE_VERSION=$ACE_VERSION

# Clone ACE and checkout specified release or fallback to stable commit
RUN git clone https://github.com/ace-step/ACE-Step.git . \
    && git checkout "$ACE_VERSION" \
    && /opt/venv/bin/pip install --no-cache-dir -r /opt/dependencies/ace.requirements.lock \
    && rm -rf .git /home/1000/.cache/pip

RUN /opt/venv/bin/python ./setup.py install 
RUN mkdir -p /app/outputs /app/checkpoints /app/logs

FROM ace-base as ace 

EXPOSE 7862 

CMD ["/opt/venv/bin/acestep", "--server_name", "0.0.0.0", "--port", "7862"]

